-- Sample industry data for the industries table
-- This file contains common industry/sector data that can be used for seeding

INSERT INTO industries (name, slug) VALUES
('Technology', 'technology'),
('Healthcare', 'healthcare'),
('Finance', 'finance'),
('Education', 'education'),
('Retail', 'retail'),
('Manufacturing', 'manufacturing'),
('Real Estate', 'real-estate'),
('Transportation', 'transportation'),
('Food & Beverage', 'food-beverage'),
('Entertainment', 'entertainment'),
('Media & Communications', 'media-communications'),
('Energy', 'energy'),
('Construction', 'construction'),
('Automotive', 'automotive'),
('Agriculture', 'agriculture'),
('Tourism & Travel', 'tourism-travel'),
('Sports & Recreation', 'sports-recreation'),
('Fashion & Beauty', 'fashion-beauty'),
('Legal Services', 'legal-services'),
('Consulting', 'consulting'),
('Non-Profit', 'non-profit'),
('Government', 'government'),
('Insurance', 'insurance'),
('Banking', 'banking'),
('E-commerce', 'e-commerce'),
('Gaming', 'gaming'),
('Biotechnology', 'biotechnology'),
('Pharmaceuticals', 'pharmaceuticals'),
('Telecommunications', 'telecommunications'),
('Logistics', 'logistics'),
('Marketing & Advertising', 'marketing-advertising'),
('Human Resources', 'human-resources'),
('Architecture & Design', 'architecture-design'),
('Environmental Services', 'environmental-services'),
('Security Services', 'security-services'),
('Event Management', 'event-management'),
('Photography', 'photography'),
('Music & Audio', 'music-audio'),
('Film & Video', 'film-video'),
('Publishing', 'publishing'),
('Software Development', 'software-development'),
('Data Analytics', 'data-analytics'),
('Artificial Intelligence', 'artificial-intelligence'),
('Cybersecurity', 'cybersecurity'),
('Cloud Services', 'cloud-services'),
('Mobile Development', 'mobile-development'),
('Web Development', 'web-development'),
('Digital Marketing', 'digital-marketing'),
('Social Media', 'social-media'),
('Content Creation', 'content-creation')
ON CONFLICT (slug) DO NOTHING;